### ISSUE TITLE
Any chance for a fully fledged working release to be put out?

### ISSUE THREAD

**Issue by carcarjg** [pboyd04/Moto.Net#1]
I can't for the life of me seem to figure out where/how to get all this working with the components you removed.

**Comment by pboyd04** [comment]
The only thing removed are 4 integer constants. I tried to remove the bare minimum to allow people to work with the system without getting sued by Motorola. They sell their development kit for many 10's of thousands of dollars. They wouldn't be happy with me releasing something for free and undercutting that. So there will probably never be a fully functional release.

**Comment by carcarjg** [comment]
Darn. Don't suppose I could get a hint for the constants XD

**Comment by pboyd04** [comment]
So I've figured out a work around if you are interested. If you go an grab TrboNet (https://trbonet.com/downloads/) Install that with the server option selected. Drop the TRBOnet.Server.exe into the same folder as the executable for this and it will detect that you don't have the constants natively and use theirs instead. 

I really wanted to use CPS or RDAC, but Motorola made it really hard to even call those methods from outside software. These guys didn't make it so hard.

**Comment by pboyd04** [comment]
Here is a working release that doesn't do audio (unless you drop in the required codec dll) and doesn't do XNL/XCMP (unless you get the constants or work around that). https://github.com/pboyd04/Moto.Net/releases/tag/v0.1.0

It will do things like log calls and allow text messaging and location queries.
